//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enferno.StormApiClient.ExportProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorMessage", Namespace="http://Enferno.Native.Schemas.ErrorMessage_v2")]
    [System.SerializableAttribute()]
    public partial class ErrorMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrchestrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement RecordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Enferno.StormApiClient.ExportProxy.Messages MessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((this.MessageIdField.Equals(value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Orchestration {
            get {
                return this.OrchestrationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrchestrationField, value) != true)) {
                    this.OrchestrationField = value;
                    this.RaisePropertyChanged("Orchestration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Xml.Linq.XElement Record {
            get {
                return this.RecordField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordField, value) != true)) {
                    this.RecordField = value;
                    this.RaisePropertyChanged("Record");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public Enferno.StormApiClient.ExportProxy.Messages Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Messages", Namespace="http://Enferno.Native.Schemas.ErrorMessage_v2", ItemName="Message", KeyName="Key", ValueName="Value")]
    [System.SerializableAttribute()]
    public class Messages : System.Collections.Generic.Dictionary<string, string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Enferno.Services", ConfigurationName="ExportProxy.ExportService")]
    public interface ExportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Enferno.Services/ExportService/ListProducts", ReplyAction="Enferno.Services/ExportService/ListProductsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Enferno.StormApiClient.ExportProxy.ErrorMessage), Action="Enferno.Services/ExportService/ListProductsErrorMessage_v2Fault", Name="ErrorMessage", Namespace="http://Enferno.Native.Schemas.ErrorMessage_v2")]
        System.ServiceModel.Channels.Message ListProducts(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Enferno.Services/ExportService/ListProducts", ReplyAction="Enferno.Services/ExportService/ListProductsResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> ListProductsAsync(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Enferno.Services/ExportService/ListProductItems", ReplyAction="Enferno.Services/ExportService/ListProductItemsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Enferno.StormApiClient.ExportProxy.ErrorMessage), Action="Enferno.Services/ExportService/ListProductItemsErrorMessage_v2Fault", Name="ErrorMessage", Namespace="http://Enferno.Native.Schemas.ErrorMessage_v2")]
        System.ServiceModel.Channels.Message ListProductItems(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Enferno.Services/ExportService/ListProductItems", ReplyAction="Enferno.Services/ExportService/ListProductItemsResponse")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> ListProductItemsAsync(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExportServiceChannel : Enferno.StormApiClient.ExportProxy.ExportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExportServiceClient : System.ServiceModel.ClientBase<Enferno.StormApiClient.ExportProxy.ExportService>, Enferno.StormApiClient.ExportProxy.ExportService {
        
        public ExportServiceClient() {
        }
        
        public ExportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Channels.Message ListProducts(System.ServiceModel.Channels.Message request) {
            return base.Channel.ListProducts(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> ListProductsAsync(System.ServiceModel.Channels.Message request) {
            return base.Channel.ListProductsAsync(request);
        }
        
        public System.ServiceModel.Channels.Message ListProductItems(System.ServiceModel.Channels.Message request) {
            return base.Channel.ListProductItems(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> ListProductItemsAsync(System.ServiceModel.Channels.Message request) {
            return base.Channel.ListProductItemsAsync(request);
        }
    }
}
